### PR TITLE
[ADD] opnsynid_payable_aging_aeroo_report

### PR DESCRIPTION
**Pull request by mikevhe18**

### CODE REVIEW

**Comment by andhit-r** [comment]
@mikevhe18 rebase dulu

**Comment by andhit-r** [comment]
@mikevhe18 rebase dulu

**Comment by mikevhe18** [comment]
@andhit-r udah di rebase mas

**Comment by andhit-r** [comment]
@mikevhe18 travis nya terluka mike hehehehe. Dicek dulu yak

**Pull request merged**
